version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: clothing-store-api

    ports:
      - "${PORT:-10000}:${PORT:-10000}"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod
      PORT: ${PORT:-10000}

    restart: always