server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: none

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: clothing-store-api

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      url: ${REDIS_URL}
      repositories:
        enabled: false



  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

app:
  mail:
    from: ${MAIL_FROM}